packages:
  - apps/*
  - packages/*
  - database

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
